default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  # username: root
  # password:
  # host: localhost

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3