default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: erb_development

test:
  <<: *default
  database: erb_test

production:
  <<: *default
  database: erb_production
  username: erb
  password: <%= ENV['ERB_DATABASE_PASSWORD'] %>
